### ISSUE TITLE
Convert Makefile to Rakefile

### ISSUE THREAD

**Issue by kemitchell** [commonform/commonform-orrick#1]
Use nice file names with spaces.

Append purchaser names to specific documents.

**Comment by anseljh** [comment]
I would love to ditch `make` and `Makefile`s. They make my brain hurt.

I experimented a bit with [Gulp](http://gulpjs.org/) today. Didn't quite get it working, but I feel it's within reach. What do you see Rake's advantages being?

**Comment by kemitchell** [comment]
Frankly, if Make won't do, I'd rather just write JS. Less to learn.
